/* confdefs.h */
#define PACKAGE_NAME "Protocol Buffers"
#define PACKAGE_TARNAME "protobuf"
#define PACKAGE_VERSION "2.5.0"
#define PACKAGE_STRING "Protocol Buffers 2.5.0"
#define PACKAGE_BUGREPORT "protobuf@googlegroups.com"
#define PACKAGE_URL ""
#define PACKAGE "protobuf"
#define VERSION "2.5.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FTRUNCATE 1
#define HAVE_MEMSET 1
#define HAVE_MKDIR 1
#define HAVE_STRCHR 1
#define HAVE_STRERROR 1
#define HAVE_STRTOL 1
#define HAVE_ZLIB 1
#define HAVE_PTHREAD 1
#define HAVE_HASH_MAP 1
#define HAVE_HASH_SET 1
#define HASH_MAP_H <tr1/unordered_map>
#define HASH_SET_H <tr1/unordered_set>
#define HASH_NAMESPACE std::tr1
#define HASH_MAP_CLASS unordered_map
#define HASH_SET_CLASS unordered_set
