ALTER TABLE `Buff` ADD `EffectType` bigint(11) DEFAULT '0' COMMENT '??????(????)  ??,??(???,??)';
ALTER TABLE `Buff` ADD `EffectValueType` bigint(11) DEFAULT '0' COMMENT '????? ??? ???--?????????,???????';
ALTER TABLE `Buff` ADD `EffectValueReferType` bigint(11) DEFAULT '0' COMMENT '???????';
ALTER TABLE `Buff` ADD `EffectTimeValue` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Buff` ADD `EffectTimeInterval` float(11,3) DEFAULT '0' COMMENT '??????0.5f??';
ALTER TABLE `Buff` ADD `WashGroupID` bigint(11) DEFAULT '0' COMMENT '??????0.5f??';
ALTER TABLE `Buff` ADD `ReverseReferType` bigint(11) DEFAULT '0' COMMENT '????,???????????????runTimeInfo,?????????';
ALTER TABLE `Buff` ADD `EffectClearOnDead` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Buff` ADD `DownSaveType` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `ChatGroup` ADD `Name` varchar(128) DEFAULT '' COMMENT '???';
ALTER TABLE `ChatGroup` ADD `CreateObject` varchar(128) DEFAULT '' COMMENT '???';
ALTER TABLE `ChatGroup` ADD `GroupMemberList` BLOB COMMENT '';
ALTER TABLE `ChatGroup` ADD `ChatList` BLOB COMMENT '';
ALTER TABLE `ConsumeData` ADD `VIPEXP` bigint(11) DEFAULT '0' COMMENT 'VIP??';
ALTER TABLE `ConsumeData` ADD `EXP` bigint(11) DEFAULT '0' COMMENT '????,?????,??????';
ALTER TABLE `ConsumeData` ADD `HP` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `ConsumeData` ADD `SP` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `ConsumeData` ADD `MP` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `ConsumeData` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `ConsumeData` ADD `Money` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Guild` ADD `Name` varchar(128) DEFAULT '' COMMENT '???';
ALTER TABLE `Guild` ADD `PresidentID` varchar(128) DEFAULT '' COMMENT '??ID';
ALTER TABLE `Guild` ADD `PresidentName` varchar(128) DEFAULT '' COMMENT '???';
ALTER TABLE `Guild` ADD `Rank` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildAD` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildDesc` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildMoney` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildLevel` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildContinueDay` bigint(11) DEFAULT '0' COMMENT '?????????';
ALTER TABLE `Guild` ADD `GuilID` varchar(128) DEFAULT '' COMMENT '??ID';
ALTER TABLE `Guild` ADD `GuilIDIcon` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildMemeberCount` bigint(11) DEFAULT '0' COMMENT '????(?????,????Record???)';
ALTER TABLE `Guild` ADD `GuildMemeberMaxCount` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Guild` ADD `GuildHonor` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildCreateTime` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Guild` ADD `GuildCreateter` bigint(11) DEFAULT '0' COMMENT '?????';
ALTER TABLE `Guild` ADD `GuildExp` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Guild` ADD `GuildStatus` bigint(11) DEFAULT '0' COMMENT '????,????,??????';
ALTER TABLE `Guild` ADD `DismissTime` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Guild` ADD `RecruitAD` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Guild` ADD `RecruitLevel` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Guild` ADD `AutoRecruit` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Guild` ADD `EctypServer` bigint(11) DEFAULT '0' COMMENT '????????';
ALTER TABLE `Guild` ADD `EctypID` bigint(11) DEFAULT '0' COMMENT '????ID';
ALTER TABLE `Guild` ADD `GuildBoss` BLOB COMMENT 'guild';
ALTER TABLE `Guild` ADD `GuildMemberList` BLOB COMMENT 'guild';
ALTER TABLE `Guild` ADD `GuildAppyList` BLOB COMMENT 'guild';
ALTER TABLE `Guild` ADD `GuildEvent` BLOB COMMENT 'guild';
ALTER TABLE `Guild` ADD `GuildHouse` BLOB COMMENT 'guild';
ALTER TABLE `Guild` ADD `GuildSkill` BLOB COMMENT 'guild';
ALTER TABLE `GuildName` ADD `GuildID` varchar(128) DEFAULT '' COMMENT '??ID';
ALTER TABLE `NPC` ADD `VIPEXP` bigint(11) DEFAULT '0' COMMENT 'VIP??';
ALTER TABLE `NPC` ADD `EXP` bigint(11) DEFAULT '0' COMMENT '????,?????,??????';
ALTER TABLE `NPC` ADD `HP` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `NPC` ADD `SP` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `NPC` ADD `MP` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `NPC` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `NPC` ADD `Money` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `NPC` ADD `X` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `NPC` ADD `Y` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `NPC` ADD `Z` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `Name` varchar(128) DEFAULT '' COMMENT '???';
ALTER TABLE `Player` ADD `Sex` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Player` ADD `Race` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Player` ADD `Camp` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Player` ADD `LastContainerID` bigint(11) DEFAULT '0' COMMENT '??????????????????';
ALTER TABLE `Player` ADD `Level` bigint(11) DEFAULT '0' COMMENT '??,???????20??,????,?????,????,????????';
ALTER TABLE `Player` ADD `ShowName` varchar(128) DEFAULT '' COMMENT '?????';
ALTER TABLE `Player` ADD `PrefabPath` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Player` ADD `FirstTarget` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Player` ADD `State` bigint(11) DEFAULT '0' COMMENT '0??1?2?3??4????5?6?????';
ALTER TABLE `Player` ADD `LogicState` bigint(11) DEFAULT '0' COMMENT '????,?????????';
ALTER TABLE `Player` ADD `CharType` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Player` ADD `Job` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Player` ADD `VIPLevel` bigint(11) DEFAULT '0' COMMENT '????,?????,??????';
ALTER TABLE `Player` ADD `VIPEXP` bigint(11) DEFAULT '0' COMMENT 'VIP??';
ALTER TABLE `Player` ADD `EXP` bigint(11) DEFAULT '0' COMMENT '????,?????,??????';
ALTER TABLE `Player` ADD `HP` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `Player` ADD `SP` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Player` ADD `MP` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `Player` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '??????';
ALTER TABLE `Player` ADD `Money` bigint(11) DEFAULT '0' COMMENT '??';
ALTER TABLE `Player` ADD `Account` varchar(128) DEFAULT '' COMMENT '?????';
ALTER TABLE `Player` ADD `ConnectKey` varchar(128) DEFAULT '' COMMENT '????????KEY';
ALTER TABLE `Player` ADD `MAXEXP` bigint(11) DEFAULT '0' COMMENT '???????';
ALTER TABLE `Player` ADD `DEAD_COUNT` bigint(11) DEFAULT '0' COMMENT '????--???????????????,?????????,????????';
ALTER TABLE `Player` ADD `RELIVE_SOUL` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Player` ADD `GUILD_NAME` varchar(128) DEFAULT '' COMMENT '??ID??';
ALTER TABLE `Player` ADD `SPOUSE_NAME` varchar(128) DEFAULT '' COMMENT '????';
ALTER TABLE `Player` ADD `TEAM_CARD` varchar(128) DEFAULT '' COMMENT '??????ID';
ALTER TABLE `Player` ADD `PVP_ATK_CARD` varchar(128) DEFAULT '' COMMENT '???PVP???';
ALTER TABLE `Player` ADD `PVP_DEF_CARD` varchar(128) DEFAULT '' COMMENT '???PVP???';
ALTER TABLE `Player` ADD `LUCKLY_CARD` varchar(128) DEFAULT '' COMMENT '??????ID';
ALTER TABLE `Player` ADD `ATK_PVP` bigint(11) DEFAULT '0' COMMENT 'PVP???';
ALTER TABLE `Player` ADD `DEF_PVP` bigint(11) DEFAULT '0' COMMENT 'PVP???';
ALTER TABLE `Player` ADD `CreditValue` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `Player` ADD `SoulValue` bigint(11) DEFAULT '0' COMMENT '???';
ALTER TABLE `Player` ADD `OnlineCount` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Player` ADD `TotalTime` bigint(11) DEFAULT '0' COMMENT '????';
ALTER TABLE `Player` ADD `Citizenship` bigint(11) DEFAULT '0' COMMENT '???????';
ALTER TABLE `Player` ADD `LastOfflineTime` varchar(128) DEFAULT '' COMMENT '??????';
ALTER TABLE `Player` ADD `OnlineTime` varchar(128) DEFAULT '' COMMENT '??????';
ALTER TABLE `Player` ADD `TotalLineTime` varchar(128) DEFAULT '' COMMENT '??????{?????????}';
ALTER TABLE `Player` ADD `GMLevel` bigint(11) DEFAULT '0' COMMENT 'GM??';
ALTER TABLE `Player` ADD `LastAttacker` varchar(128) DEFAULT '' COMMENT '';
ALTER TABLE `Player` ADD `X` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `Y` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `Z` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `TargetX` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `TargetY` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `TargetZ` float(11,3) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `PathStep` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `Player` ADD `GameID` bigint(11) DEFAULT '0' COMMENT '????ID';
ALTER TABLE `Player` ADD `GateID` bigint(11) DEFAULT '0' COMMENT '?????ID';
ALTER TABLE `Player` ADD `GuildID` varchar(128) DEFAULT '' COMMENT '??ID';
ALTER TABLE `Player` ADD `PlayerViewItem` BLOB COMMENT '';
ALTER TABLE `Player` ADD `PlayerHero` BLOB COMMENT '';
ALTER TABLE `Player` ADD `BagEquipList` BLOB COMMENT '????';
ALTER TABLE `Player` ADD `BagItemList` BLOB COMMENT '????';
ALTER TABLE `Player` ADD `EctypeList` BLOB COMMENT '????';
ALTER TABLE `Player` ADD `DropItemList` BLOB COMMENT '?????';
ALTER TABLE `Player` ADD `SkillTable` BLOB COMMENT '';
ALTER TABLE `Player` ADD `TaskMonsterList` BLOB COMMENT '?????';
ALTER TABLE `Player` ADD `TaskList` BLOB COMMENT '???';
ALTER TABLE `Player` ADD `BuildingList` BLOB COMMENT '';
ALTER TABLE `Player` ADD `BuildingListProduce` BLOB COMMENT '';
ALTER TABLE `Shop` ADD `Type` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `Shop` ADD `ItemID` varchar(128) DEFAULT '' COMMENT '';
ALTER TABLE `Shop` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `Shop` ADD `Steel` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `Shop` ADD `Stone` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `Shop` ADD `Diamond` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `Shop` ADD `Level` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFuncResources` ADD `Atlas_ResID` varchar(128) DEFAULT '' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_INFO` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_BOOOST` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_LVLUP` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_CREATE_SOLDER` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_CREATE_SPEEL` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_RESEARCH` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_COLLECT_GOLD` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_COLLECT_STONE` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_COLLECT_STEEL` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_COLLECT_DIAMOND` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_SELL` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_REPAIR` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_CANCEL` bigint(11) DEFAULT '0' COMMENT '';
ALTER TABLE `StateFunction` ADD `EFT_FINISH` bigint(11) DEFAULT '0' COMMENT '';
